'use strict';
const CFG = {
  PROXIES: [
    u=>`https://api.allorigins.win/get?url=${encodeURIComponent(u)}`,
    u=>`https://corsproxy.io/?${encodeURIComponent(u)}`,
    u=>`https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(u)}`,
  ],
  FEEDS: {
    tech: [
      {name:'TechCrunch',    url:'https://techcrunch.com/feed/',                              key:'tc'},
      {name:'The Verge',     url:'https://www.theverge.com/rss/index.xml',                   key:'verge'},
      {name:'Wired',         url:'https://www.wired.com/feed/rss',                           key:'wired'},
      {name:'Ars Technica',  url:'https://feeds.arstechnica.com/arstechnica/index',           key:'ars'},
      {name:'Engadget',      url:'https://www.engadget.com/rss.xml',                         key:'engadget'},
      {name:'ZDNet',         url:'https://www.zdnet.com/news/rss.xml',                       key:'zdnet'},
      {name:'CNET',          url:'https://www.cnet.com/rss/news/',                           key:'cnet'},
      {name:'MIT Tech',      url:'https://www.technologyreview.com/feed/',                   key:'mit'},
      {name:'Win Central',   url:'https://www.windowscentral.com/feed',                      key:'wc'},
    ],
    gaming: [
      {name:'IGN',           url:'https://www.ign.com/articles.rss',                         key:'ign'},
      {name:'Kotaku',        url:'https://kotaku.com/rss',                                   key:'kotaku'},
      {name:'Eurogamer',     url:'https://www.eurogamer.net/feed',                           key:'eurogamer'},
      {name:'GameSpot',      url:'https://www.gamespot.com/feeds/mashup/',                   key:'gamespot'},
      {name:'PC Gamer',      url:'https://www.pcgamer.com/rss/',                             key:'pcgamer'},
      {name:'Rockstar',      url:'https://www.rockstargames.com/newswire/feed.rss',          key:'rockstar'},
    ],
    world: [
      {name:'BBC',           url:'https://feeds.bbci.co.uk/news/world/rss.xml',                    key:'bbc'},
      {name:'AP News',       url:'https://rsshub.app/apnews/topics/apf-topnews',                   key:'ap'},
      {name:'Al Jazeera',    url:'https://www.aljazeera.com/xml/rss/all.xml',                      key:'aljazeera'},
      {name:'The Guardian',  url:'https://www.theguardian.com/world/rss',                          key:'guardian'},
      {name:'CNBC World',    url:'https://www.cnbc.com/id/100003114/device/rss/rss.html',          key:'cnbc'},
      {name:'NPR World',     url:'https://feeds.npr.org/1004/rss.xml',                             key:'npr'},
      {name:'Sky News',      url:'https://feeds.skynews.com/feeds/rss/world.xml',                  key:'skynews'},
    ],
    india: [
      {name:'The Hindu',     url:'https://www.thehindu.com/news/national/feeder/default.rss',key:'hindu'},
      {name:'Indian Express',url:'https://indianexpress.com/feed/',                          key:'ie'},
      {name:'NDTV',          url:'https://feeds.feedburner.com/ndtvnews-top-stories',        key:'ndtv'},
      {name:'Times of India',url:'https://timesofindia.indiatimes.com/rssfeedstopstories.cms',key:'toi'},
      {name:'Hindustan Times',url:'https://www.hindustantimes.com/rss/topnews/rssfeed.xml', key:'ht'},
      {name:'Moneycontrol',  url:'https://www.moneycontrol.com/rss/latestnews.xml',         key:'mc'},
    ],
    tamilnadu: [
      {name:'The Hindu TN',  url:'https://www.thehindu.com/news/national/tamil-nadu/feeder/default.rss', key:'hindu-tn'},
      {name:'TOI Chennai',   url:'https://timesofindia.indiatimes.com/rssfeeds/2802579.cms',key:'toi-chen'},
      {name:'IE Tamil Nadu', url:'https://indianexpress.com/section/india/tamil-nadu/feed/',key:'ie-tn'},
      {name:'DT Next',       url:'https://www.dtnext.in/rss/',                              key:'dtnext'},
      {name:'News18 TN',     url:'https://www.news18.com/rss/politics.xml',                 key:'news18tn'},
    ],
    science: [
      {name:'NASA',          url:'https://www.nasa.gov/news-release/feed/',                 key:'nasa'},
      {name:'ESA',           url:'https://www.esa.int/rssfeed/Our_Activities/Space_Science',key:'esa'},
      {name:'Space.com',     url:'https://www.space.com/feeds/all',                         key:'space'},
      {name:'Sci American',  url:'https://www.scientificamerican.com/feed/rss/',            key:'sciam'},
      {name:'New Scientist', url:'https://www.newscientist.com/feed/home/',                 key:'newscientist'},
    ],
    cyber: [
      {name:'Krebs',         url:'https://krebsonsecurity.com/feed/',                        key:'krebs'},
      {name:'BleepingComp',  url:'https://www.bleepingcomputer.com/feed/',                  key:'bleeping'},
      {name:'Hacker News',   url:'https://feeds.feedburner.com/TheHackersNews',             key:'thn'},
      {name:'CyberNews',     url:'https://cybernews.com/feed/',                             key:'cybernews'},
    ],
    ai: [
      {name:'MIT Tech',      url:'https://www.technologyreview.com/feed/',                          key:'mit-ai'},
      {name:'The Verge AI',  url:'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',key:'verge-ai'},
      {name:'Ars AI',        url:'https://feeds.arstechnica.com/arstechnica/index',                key:'ars-ai'},
      {name:'Wired AI',      url:'https://www.wired.com/feed/tag/artificial-intelligence/latest/rss',key:'wired-ai'},
      {name:'VentureBeat AI',url:'https://venturebeat.com/category/ai/feed/',                     key:'vb-ai'},
    ],
    finance: [
      {name:'CNBC Finance',  url:'https://www.cnbc.com/id/10000664/device/rss/rss.html',          key:'cnbc-f'},
      {name:'Moneycontrol',  url:'https://www.moneycontrol.com/rss/latestnews.xml',               key:'mc-f'},
      {name:'Financial Times',url:'https://www.ft.com/news-feed?format=rss',                      key:'ft'},
      {name:'Forbes',        url:'https://www.forbes.com/business/feed/',                         key:'forbes'},
      {name:'Economic Times',url:'https://economictimes.indiatimes.com/rssfeedsdefault.cms',      key:'et'},
    ],
  },
  HN:     'https://hacker-news.firebaseio.com/v0/',
  GITHUB: 'https://api.github.com/search/repositories?q=created:>__DATE__&sort=stars&order=desc&per_page=8',
  SO:     'https://api.stackexchange.com/2.3/questions?order=desc&sort=votes&site=stackoverflow&pagesize=6&filter=withbody',
  BREAKING_KEYWORDS: ['breaking','urgent','alert','emergency','crisis','attack','explosion','earthquake','war','invasion','coup','assassination','disaster','critical','flash','developing'],
  TRENDING_KEYWORDS: ['record','historic','milestone','first ever','major','landmark','largest','biggest','breakthrough'],
};
